"""Add Investment model

Revision ID: 899bebb3e1b1
Revises: 8da7396b1f6f
Create Date: 2026-07-04 10:47:48.768877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899bebb3e1b1'
down_revision = '8da7396b1f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('average_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment')
    # ### end Alembic commands ###
